In [1]:
ls

maze2d_100x100.npy*  maze2d_3x3.npy*  Untitled.ipynb*
maze2d_10x10.npy*    maze2d_5x5.npy*


In [2]:
import numpy as np
data = np.load('maze2d_5x5.npy')


In [3]:
data

array([[2, 4, 1, 2, 1],
       [4, 4, 8, 4, 2],
       [8, 1, 1, 1, 1],
       [2, 4, 4, 4, 8],
       [4, 8, 1, 1, 1]])

In [4]:
dat3 = np.load('maze2d_3x3.npy')

In [5]:
dat3

array([[2, 1, 1],
       [2, 2, 8],
       [4, 8, 8]])

In [6]:
dat10 = np.load('maze2d_10x10.npy')

In [7]:
dat10

array([[2, 4, 2, 1, 1, 1, 1, 4, 4, 2],
       [4, 8, 2, 2, 1, 1, 8, 2, 1, 1],
       [2, 1, 1, 4, 2, 8, 8, 4, 4, 2],
       [4, 8, 2, 8, 4, 2, 8, 1, 1, 2],
       [4, 2, 1, 8, 2, 4, 4, 2, 8, 2],
       [8, 2, 4, 8, 4, 4, 2, 4, 8, 2],
       [8, 2, 8, 4, 2, 1, 1, 1, 1, 2],
       [8, 4, 8, 8, 2, 2, 4, 4, 8, 2],
       [8, 1, 2, 1, 2, 2, 8, 2, 1, 1],
       [4, 8, 1, 8, 1, 4, 8, 1, 4, 8]])

In [9]:
np.zeros(2,dtype=int)

array([0, 0])

In [10]:
np.array((10,10)) - np.array((1, 1))

array([9, 9])

In [11]:
np.array([6,4])

array([6, 4])